<template><div><div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token function">addEntityPoint</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">let</span> entityPoint <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Webgis<span class="token punctuation">.</span>Entity</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">id</span><span class="token operator">:</span> <span class="token string">'entityPoint0'</span><span class="token punctuation">,</span>
        <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'entityPoint'</span><span class="token punctuation">,</span>
        <span class="token literal-property property">position</span><span class="token operator">:</span> WebgisWebgis<span class="token punctuation">.</span>Cartesian3<span class="token punctuation">.</span><span class="token function">fromDegrees</span><span class="token punctuation">(</span><span class="token number">125.2</span><span class="token punctuation">,</span> <span class="token number">40.5</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
        <span class="token literal-property property">point</span><span class="token operator">:</span> <span class="token punctuation">{</span>
            <span class="token literal-property property">color</span><span class="token operator">:</span> Webgis<span class="token punctuation">.</span>Color<span class="token punctuation">.</span><span class="token constant">YELLOWGREEN</span><span class="token punctuation">,</span>
            <span class="token literal-property property">pixelSize</span><span class="token operator">:</span> <span class="token number">40</span><span class="token punctuation">,</span>
            <span class="token literal-property property">scaleByDistance</span><span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">Webgis<span class="token punctuation">.</span>NearFarScalar</span><span class="token punctuation">(</span><span class="token number">1.5e2</span><span class="token punctuation">,</span> <span class="token number">2.0</span><span class="token punctuation">,</span> <span class="token number">1.5e7</span><span class="token punctuation">,</span> <span class="token number">0.1</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
            <span class="token literal-property property">translucencyByDistance</span><span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">Webgis<span class="token punctuation">.</span>NearFarScalar</span><span class="token punctuation">(</span>
                <span class="token number">1.5e2</span><span class="token punctuation">,</span>
                <span class="token number">1.0</span><span class="token punctuation">,</span>
                <span class="token number">1.5e8</span><span class="token punctuation">,</span>
                <span class="token number">0.0</span>
            <span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token keyword">let</span> pointGeom <span class="token operator">=</span> window<span class="token punctuation">.</span>viewer<span class="token punctuation">.</span>entities<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>entityPoint<span class="token punctuation">)</span>
    window<span class="token punctuation">.</span>viewer<span class="token punctuation">.</span><span class="token function">zoomTo</span><span class="token punctuation">(</span>pointGeom<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="D:\riceSand\three.js封装--webgis场景-文档\three.jsforgisAPIdocs\docs\example\img\point.png" alt="点" tabindex="0" loading="lazy"><figcaption>点</figcaption></figure>
</div></template>


