<template><div><p><strong>拾取模型点</strong></p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> viewer <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Webgis<span class="token punctuation">.</span>Viewer</span><span class="token punctuation">(</span>WebgisContainer<span class="token punctuation">)</span>
viewer<span class="token punctuation">.</span>screenSpaceEventHandler<span class="token punctuation">.</span><span class="token function">setInputAction</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">clickEvent</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">var</span> ray1 <span class="token operator">=</span> viewer<span class="token punctuation">.</span>camera<span class="token punctuation">.</span><span class="token function">getPickRay</span><span class="token punctuation">(</span>clickEvent<span class="token punctuation">.</span>position<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">var</span> pick <span class="token operator">=</span> viewer<span class="token punctuation">.</span>scene<span class="token punctuation">.</span><span class="token function">pickPosition</span><span class="token punctuation">(</span>clickEvent<span class="token punctuation">.</span>position<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">var</span> pickModel <span class="token operator">=</span> viewer<span class="token punctuation">.</span>scene<span class="token punctuation">.</span><span class="token function">pick</span><span class="token punctuation">(</span>clickEvent<span class="token punctuation">.</span>position<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>pickModel <span class="token operator">&amp;&amp;</span> pick <span class="token operator">&amp;&amp;</span> <span class="token operator">!</span>pickModel<span class="token punctuation">.</span>id<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token keyword">var</span> height <span class="token operator">=</span> WebgisWebgisWebgis<span class="token punctuation">.</span>Cartographic<span class="token punctuation">.</span><span class="token function">fromCartesian</span><span class="token punctuation">(</span>pick<span class="token punctuation">)</span><span class="token punctuation">.</span>height<span class="token punctuation">;</span>
                <span class="token keyword">var</span> lat <span class="token operator">=</span> WebgisWebgis<span class="token punctuation">.</span>Math<span class="token punctuation">.</span><span class="token function">toDegrees</span><span class="token punctuation">(</span>Cesium<span class="token punctuation">.</span>Cartographic<span class="token punctuation">.</span><span class="token function">fromCartesian</span><span class="token punctuation">(</span>pick<span class="token punctuation">)</span><span class="token punctuation">.</span>latitude<span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token keyword">var</span> lng <span class="token operator">=</span> Webgis<span class="token punctuation">.</span>Math<span class="token punctuation">.</span><span class="token function">toDegrees</span><span class="token punctuation">(</span>Cesium<span class="token punctuation">.</span>Cartographic<span class="token punctuation">.</span><span class="token function">fromCartesian</span><span class="token punctuation">(</span>pick<span class="token punctuation">)</span><span class="token punctuation">.</span>longitude<span class="token punctuation">)</span><span class="token punctuation">;</span>
                cartesian <span class="token operator">=</span> Webgis<span class="token punctuation">.</span>Cartesian3<span class="token punctuation">.</span><span class="token function">fromDegrees</span><span class="token punctuation">(</span>lng<span class="token punctuation">,</span> lat<span class="token punctuation">,</span> height<span class="token punctuation">)</span><span class="token punctuation">;</span>
                 console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'模型高度点'</span><span class="token punctuation">,</span>cartesian<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
 <span class="token punctuation">}</span><span class="token punctuation">,</span> Webgis<span class="token punctuation">.</span>ScreenSpaceEventType<span class="token punctuation">.</span><span class="token constant">LEFT_CLICK</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


